<h3>ğŸ›  Tech Stack</h3>

- ğŸ’» &nbsp; C# | JavaScript | React | C++ |MERN  
- ğŸŒ &nbsp; FrontEnd | React | HTML | CSS | JavaScript | Bootstrap 
- ğŸ›¢ &nbsp; MySQL | Firebase | Postman
- ğŸ”§ &nbsp; Visual Studio code  | Git
- ğŸ–¥ &nbsp; Photoshop | Figma


<h3> ğŸ¤ğŸ» Connect with Me </h3>

<p align="center">
&nbsp; <a href="https://www.instagram.com/hoangpv.22/" target="_blank" rel="noopener noreferrer"><img src="https://img.icons8.com/plasticine/100/000000/twitter.png" width="50" /></a>  
&nbsp; <a href="https://www.instagram.com/hoangpv.22/" target="_blank" rel="noopener noreferrer"><img src="https://img.icons8.com/plasticine/100/000000/instagram-new.png" width="50" /></a>  
&nbsp; <a href="https://www.instagram.com/hoangpv.22/" target="_blank" rel="noopener noreferrer"><img src="https://img.icons8.com/plasticine/100/000000/linkedin.png" width="50" /></a>
&nbsp; <a href="mailto:phanviethoang187@gmail.com" target="_blank" rel="noopener noreferrer"><img src="https://img.icons8.com/plasticine/100/000000/gmail.png"  width="50" /></a>
</p>

â­ï¸ From [viethoanguet](https://github.com/viethoanguet)
